services:
  bot:
    build: .
    container_name: babulletinbot
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    env_file:
      - .env
    volumes:
      - ./bulletin_cache:/app/bulletin_cache
