[project]
name = "babulletinbotv2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "mammoth>=1.12.2",
    "pymupdf>=1.28.2",
    "python-dotenv>=1.2.1",
    "python-telegram-bot[job-queue]>=22.5",
    "requests>=2.32.5",
    "tenacity>=9.1.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
